name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3']
        rails-version: ['6.1', '7.0', '7.1', '8.0']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: false
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        
    - name: Override Rails version
      run: |
        # Create a temporary Gemfile without the rails and sqlite3 gems
        grep -v '^gem "rails"\|^gem "sqlite3"' Gemfile > Gemfile.tmp
        mv Gemfile.tmp Gemfile
        # Add the specific Rails version
        echo "gem 'rails', '~> ${{ matrix.rails-version }}'" >> Gemfile
        # Add appropriate sqlite3 version based on Rails version
        if [[ "${{ matrix.rails-version }}" == "6.1" || "${{ matrix.rails-version }}" == "7.0" ]]; then
          echo "gem 'sqlite3', '~> 1.4'" >> Gemfile
        else
          echo "gem 'sqlite3', '~> 2.1'" >> Gemfile
        fi
        bundle update rails activestorage activesupport activerecord sqlite3
        
    - name: Run tests
      run: bundle exec rspec