name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3']
        rails-version: ['6.1', '7.0', '7.1', '8.0']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        
    - name: Override Rails version
      run: |
        # Remove the existing rails gem line
        sed -i '/^gem "rails"/d' Gemfile
        # Add the specific Rails version
        echo "gem 'rails', '~> ${{ matrix.rails-version }}'" >> Gemfile
        bundle update rails activestorage activesupport activerecord
        
    - name: Run tests
      run: bundle exec rspec